"""
agents/proposal_agent.py
ProposalAgent — generates proposals, applications, and reply drafts.
Uses DeepSeek-R1 via Ollama. Respects rate limiting via sleep.
"""
import time
from agents.base_agent import BaseAgent


class ProposalAgent(BaseAgent):
    name = "proposal"

    def run(self, context: dict) -> dict:
        jobs        = context.get("qualified_jobs", [])
        your_name   = context.get("your_name", "Ibrahim")
        your_skills = context.get("your_skills", "Python, automation, web scraping, AI integration, FastAPI")
        max_generate = context.get("max_generate", 5)
        feed        = []
        generated   = []

        for job in jobs[:max_generate]:
            feed.append(self.log(f"Generating for: {job.get('title','')[:50]}"))
            try:
                text = self._generate(job, your_name, your_skills)
                entry = {
                    "job_id":           job.get("job_id"),
                    "platform":         job.get("platform"),
                    "job_title":        job.get("title"),
                    "job_desc":         job.get("description",""),
                    "budget":           job.get("budget",""),
                    "job_link":         job.get("link",""),
                    "proposal_text":    text,
                    "confidence":       job.get("score", 50),
                    "can_auto_work":    False,
                    "work_type":        "application",
                    "work_reason":      "Generated by ProposalAgent",
                }
                self._save(entry)
                generated.append(entry)
                feed.append(self.log(f"Generated proposal for: {job.get('title','')[:40]}"))
                time.sleep(1)  # rate limit — don't hammer Ollama
            except Exception as e:
                feed.append(self.log(f"Failed {job.get('title','')[:30]}: {e}", "error"))

        feed.append(self.log(f"ProposalAgent complete: {len(generated)} generated"))
        return {"generated": generated, "feed": feed}

    def _generate(self, job: dict, your_name: str, your_skills: str) -> str:
        from services.deepseek_service import call_model
        platform = job.get("platform", "freelance")
        prompt = f"""Write a professional job application for {platform}.

Job Title: {job.get('title','')}
Company: {job.get('company','the company')}
Description: {job.get('description','')}
Budget: {job.get('budget','not specified')}

Applicant: {your_name}
Skills: {your_skills}

Rules:
- Under 200 words
- Open by proving you understand the specific problem
- Mention 1-2 directly relevant skills
- Include a realistic timeline
- End with a confident call to action
- Sign off as: {your_name}
Output ONLY the application/proposal text."""
        return call_model(prompt)

    def _save(self, entry: dict):
        from models.db import conn
        from datetime import datetime, timezone
        now = datetime.now(timezone.utc).isoformat()
        with conn() as db:
            # Check if already generated for this job_id
            exists = db.execute(
                "SELECT id FROM proposals WHERE job_id=?", (entry["job_id"],)
            ).fetchone()
            if not exists:
                db.execute(
                    """INSERT INTO proposals
                       (job_id,platform,job_title,job_desc,budget,job_link,
                        proposal_text,confidence,can_auto_work,work_type,work_reason,
                        status,created_at,updated_at)
                       VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?)""",
                    (entry["job_id"], entry["platform"], entry["job_title"],
                     entry["job_desc"], entry["budget"], entry["job_link"],
                     entry["proposal_text"], entry["confidence"],
                     1 if entry["can_auto_work"] else 0,
                     entry["work_type"], entry["work_reason"],
                     "draft", now, now)
                )
