"""
agents/proposal_agent.py
ProposalAgent — generates proposals, applications, and reply drafts.
Uses the local LLM via Ollama. Respects rate limiting via sleep.

Contract: run(context) accepts EITHER
  {"qualified_jobs": [job, ...]}   — batch mode (orchestrator pipeline)
  {"job": job}                     — single-job mode (V9 core calls per job)
Both paths generate, save to the proposals table, and return the entries.
The old mismatch (core passing "job", agent reading "qualified_jobs") was the
root cause of the permanent "ProposalAgent complete: 0 generated" log line.
"""
import time
from agents.base_agent import BaseAgent


class ProposalAgent(BaseAgent):
    name = "proposal"

    def run(self, context: dict) -> dict:
        jobs = context.get("qualified_jobs")
        if jobs is None:
            single = context.get("job")
            jobs = [single] if single else []
        profile = self._profile(context)
        max_generate = int(context.get("max_generate", profile.get("max_generate", 10)))
        feed        = []
        generated   = []

        for job in jobs[:max_generate]:
            feed.append(self.log(f"Generating for: {job.get('title','')[:50]}"))
            try:
                text = self._generate(job, profile)
                if not text or text.startswith(("[No AI available", "[Ollama error")):
                    feed.append(self.log(
                        f"LLM unavailable — used template for: {job.get('title','')[:40]}",
                        "warning"))
                    text = self._template(job, profile)
                entry = {
                    "job_id":           job.get("job_id"),
                    "platform":         job.get("platform"),
                    "job_title":        job.get("title"),
                    "job_desc":         job.get("description",""),
                    "budget":           job.get("budget",""),
                    "job_link":         job.get("link",""),
                    "proposal_text":    text,
                    "confidence":       job.get("score", 50),
                    "can_auto_work":    False,
                    "work_type":        "application",
                    "work_reason":      "Generated by ProposalAgent",
                }
                self._save(entry)
                generated.append(entry)
                feed.append(self.log(f"Generated proposal for: {job.get('title','')[:40]}"))
                time.sleep(1)  # rate limit — don't hammer Ollama
            except Exception as e:
                feed.append(self.log(f"Failed {job.get('title','')[:30]}: {e}", "error"))

        feed.append(self.log(f"ProposalAgent complete: {len(generated)} generated"))
        return {"generated": generated, "feed": feed}

    def _profile(self, context: dict) -> dict:
        """Persistent profile, with any per-run overrides from the caller."""
        try:
            from services.profile_service import get_profile
            profile = get_profile()
        except Exception:
            profile = {"name": "Ibrahim",
                       "skills": "Python, automation, web scraping, AI integration, FastAPI"}
        if context.get("your_name"):
            profile["name"] = context["your_name"]
        if context.get("your_skills"):
            profile["skills"] = context["your_skills"]
        return profile

    def _generate(self, job: dict, profile: dict) -> str:
        from services.deepseek_service import call_model
        from services.profile_service import prompt_block
        platform = job.get("platform", "freelance")
        prompt = f"""Write a professional job application for {platform}.

Job Title: {job.get('title','')}
Company: {job.get('company','the company')}
Description: {job.get('description','')}
Budget: {job.get('budget','not specified')}

{prompt_block(profile)}

Rules:
- Under 200 words
- Open by proving you understand the specific problem
- Mention 1-2 directly relevant skills
- Include a realistic timeline
- End with a confident call to action
- Sign off as: {profile.get('name','')}
Output ONLY the application/proposal text."""
        return call_model(prompt)

    def _template(self, job: dict, profile: dict) -> str:
        """Offline fallback so a missing LLM never produces zero output."""
        name = profile.get("name", "")
        return (f"Hi,\n\nI read your post \"{job.get('title','')}\" and it lines up "
                f"directly with what I do: {profile.get('skills','')}. "
                f"I can start right away and will share progress early so you can "
                f"course-correct before anything is final.\n\n"
                f"When would you like to see a first result?\n\n— {name}")

    def _save(self, entry: dict):
        from models.db import conn
        from datetime import datetime, timezone
        now = datetime.now(timezone.utc).isoformat()
        with conn() as db:
            # Check if already generated for this job_id
            exists = db.execute(
                "SELECT id FROM proposals WHERE job_id=?", (entry["job_id"],)
            ).fetchone()
            if not exists:
                db.execute(
                    """INSERT INTO proposals
                       (job_id,platform,job_title,job_desc,budget,job_link,
                        proposal_text,confidence,can_auto_work,work_type,work_reason,
                        status,created_at,updated_at)
                       VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?)""",
                    (entry["job_id"], entry["platform"], entry["job_title"],
                     entry["job_desc"], entry["budget"], entry["job_link"],
                     entry["proposal_text"], entry["confidence"],
                     1 if entry["can_auto_work"] else 0,
                     entry["work_type"], entry["work_reason"],
                     "draft", now, now)
                )
